site: bzhangcw.io

permalink: pretty

email: bzhangcw@github.com
description: >- # this means to ignore newlines until "baseurl:"
  bzhangcw.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bzhangcw.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bzhangcw

# Google Analytics
google_analytics: G-H06CBKXSEK  # Replace with your actual Measurement ID

highlighter: rouge

exclude:
  - .jekyll-cache
  - netlify
  - howto

markdown: kramdown
kramdown:
  math_engine: katex
sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
