[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

